services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb_container
    ports:
      - "27007:27017"
    volumes:
      - mongodata:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend_network
    restart: always

networks:
  backend_network:

volumes:
  mongodata: