services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb_container
    ports:
      - "27007:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - backend_network
    restart: always

networks:
  backend_network:
